### ISSUE TITLE
Error: http provider parse response error

### ISSUE THREAD

**Issue by eden202306** [toncenter/tonweb#231]
async function get_usdt_balance() {
            const tonweb = new TonWeb();
            const jettonMinter = new TonWeb.token.jetton.JettonMinter(tonweb.provider, { address: new TonWeb.utils.Address("EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs") });
            const jettonWalletAddress = await jettonMinter.getJettonWalletAddress(new TonWeb.utils.Address(address));
            console.log(jettonWalletAddress)
           
            const jettonWallet = new TonWeb.token.jetton.JettonWallet(tonweb.provider, {
                address: jettonWalletAddress
            });

            try {
                const jettonBalance = (await jettonWallet.getData()).balance;
                console.log(jettonBalance);
            } catch (error) {
                console.error('error:', error);
            }

            console.log(jettonData)
        }

The error reported when executing the code is as follows：
test.html:198  error: Error: http provider parse response error
    at o.parseResponse (tonweb.js:2:230330)
    at a.call2 (tonweb.js:2:228520)
    at async h.getData (tonweb.js:2:277780)
    at async get_usdt_balance (test.html:195:40)

**Comment by Mahya0933** [comment]
``Check if you're eligible to receive rewards of up to 500,000 NOT and 3,000 USD₮ by clicking the "Earn" button.

**Comment by Mahya0933** [comment]
Good

**Comment by alexcraviotto** [comment]
Did you fix that?

**Comment by redbitbbe** [comment]
I also encountered this problem

**Comment by redbitbbe** [comment]
![image](https://github.com/user-attachments/assets/047d8fd9-d9d2-4400-8238-554c98b09f59)
The exit_code reported here is -131

**Comment by qzmer1104** [comment]
> ![image](https://private-user-images.githubusercontent.com/155608760/364359456-047d8fd9-d9d2-4400-8238-554c98b09f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDUyMTAsIm5iZiI6MTcyOTYwNDkxMCwicGF0aCI6Ii8xNTU2MDg3NjAvMzY0MzU5NDU2LTA0N2Q4ZmQ5LWQ5ZDItNDQwMC04MjM4LTU1NGM5OGIwOWY1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMzQ4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmRlYzNmNmE1ZmIzYzIzMWRlODhlNzRiN2MwMmU0ZDNjNGNiMjJjOWRhMzQ2Y2NiNDdmNGY2YzgxYjlmMjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zapNBCf1NyYDtEG2V1PoYAb1zQkxiArz6cDRdxlneeY) The exit_code reported here is -131

same question!!!

**Comment by khalilmosavi** [comment]
async function get_usdt_balance() {
        const tonweb = new TonWeb();
        const jettonMinter = new TonWeb.token.jetton.JettonMinter(tonweb.provider, { address: new TonWeb.utils.Address("EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs") });
        const jettonWalletAddress = await jettonMinter.getJettonWalletAddress(new TonWeb.utils.Address(address));
        console.log(jettonWalletAddress)
       
        const jettonWallet = new TonWeb.token.jetton.JettonWallet(tonweb.provider, {
            address: jettonWalletAddress
        });

        try {
            const jettonBalance = (await jettonWallet.getData()).balance;
            console.log(jettonBalance);
        } catch (error) {
            console.error('error:', error);
        }

        console.log(jettonData)
    }

**Comment by chefReyMysterio** [comment]
> ```
> async function get_usdt_balance() {
>     const tonweb = new TonWeb();
>     const jettonMinter = new TonWeb.token.jetton.JettonMinter(tonweb.provider, { address: new TonWeb.utils.Address("EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs") });
>     const jettonWalletAddress = await jettonMinter.getJettonWalletAddress(new TonWeb.utils.Address(address));
>     console.log(jettonWalletAddress)
>    
>     const jettonWallet = new TonWeb.token.jetton.JettonWallet(tonweb.provider, {
>         address: jettonWalletAddress
>     });
> 
>     try {
>         const jettonBalance = (await jettonWallet.getData()).balance;
>         console.log(jettonBalance);
>     } catch (error) {
>         console.error('error:', error);
>     }
> 
>     console.log(jettonData)
> }
> ```

i do the same code, but isn't work for me. i got same error "http provider parse response error"

**Comment by nqmgaming** [comment]
I have same problem :(

**Comment by coin369** [comment]
I have same problem :(

**Comment by coin369** [comment]
const walletAddress1 = this.rawAddress;

        var address = this.rawAddress;

          var tonweb = new  TonWeb(new TonWeb.HttpProvider('https://testnet.toncenter.com/api/v2/jsonRPC'));
          const jettonMinter = new TonWeb.token.jetton.JettonMinter(tonweb.provider, { address: new TonWeb.utils.Address(x1) });
          const jettonWalletAddress = await jettonMinter.getJettonWalletAddress(new TonWeb.utils.Address(address));

         
         
          const jettonWallet = new TonWeb.token.jetton.JettonWallet(tonweb.provider, {
              address: jettonWalletAddress
          });

          try {
              const jettonBalance = (await jettonWallet.getData());
              console.log("BTT",jettonBalance);
          } catch (error) {
              console.error('error:', error);
          }

          
DONE.

**Comment by zzeindal** [comment]
Guys, how did you solve the problem? What version are you using? new TonWeb.token.jetton.JettonMinter requires adminAddress and etc
